/* Agent Platform 前端验收台：覆盖智能体、厂商配置、模型与 SSE 调试。 */
(() => {
  'use strict';
  const API_BASE = window.API_BASE || '';
  const STORE = 'agent_platform_session';
  const codes = {999:'数据库或服务调用失败',1001:'用户名已存在',1002:'邮箱已存在',1003:'密码格式错误',1004:'无效 Token',1005:'用户不存在',1006:'邮箱未验证',1007:'Token 生成失败',2001:'智能体不存在',2002:'厂商配置不存在',2003:'模型不存在',2004:'厂商配置不可用',2005:'模型不可用',2006:'智能体模型配置不完整',2007:'不支持的模型厂商',2008:'厂商配置正在被模型使用',2009:'智能体尚未发布或配置未完成',3001:'工具已存在',3002:'工具不存在',3003:'系统工具未注册',3004:'工具已停用',3005:'不支持的工具类型',3006:'MCP 工具缺少配置',400:'请求参数不合法',401:'未登录或 Token 已过期',500:'服务端错误'};
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => Array.from(root.querySelectorAll(s));
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const enc = encodeURIComponent;
  let session = {token:'',refreshToken:'',userInfo:null};
  let agents = [], providers = [], models = [], tools = [], editing = null, chatAbort = null;

  function load(){ try { session = {...session,...JSON.parse(localStorage.getItem(STORE)||'{}')}; } catch (_){} }
  function save(){ localStorage.setItem(STORE, JSON.stringify(session)); }
  function clear(){ session={token:'',refreshToken:'',userInfo:null}; localStorage.removeItem(STORE); }
  function toast(text, error=false){ const n=document.createElement('div'); n.className='toast'+(error?' error':''); n.textContent=text; $('#toastWrap').append(n); setTimeout(()=>n.remove(),3500); }
  function log(method,path,status,data,ms){ const empty=$('#requestLog .muted'); if(empty) $('#requestLog').innerHTML=''; const line=document.createElement('p'); line.className='log-line'; const ok=String(status).startsWith('2'); let detail=''; if(data !== undefined){ try{detail=typeof data==='string'?data:JSON.stringify(data);}catch(_){detail='[无法序列化]';} if(detail.length>460) detail=detail.slice(0,460)+'…'; } line.innerHTML=`<span class="method">${esc(method)}</span> ${esc(path)} <span class="${ok?'ok':'bad'}">${esc(status)}</span> ${ms?esc(ms+'ms'):''}${detail?'\n  '+esc(detail):''}`; $('#requestLog').append(line); $('#requestLog').scrollTop=$('#requestLog').scrollHeight; }
  function errorText(r){ return (r&&r.msg) || codes[r&&r.code] || '请求未成功'; }
  async function api(method,path,body,auth=true){ const started=performance.now(); const headers={'Content-Type':'application/json'}; if(auth&&session.token)headers.Authorization='Bearer '+session.token; try{ const response=await fetch(API_BASE+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}); const raw=await response.text(); let payload; try{payload=raw?JSON.parse(raw):{};}catch(_){payload=raw;} log(method,path,response.status,payload,Math.round(performance.now()-started)); if(!response.ok || (payload && payload.code !== undefined && payload.code !== 200)) return {...(typeof payload==='object'?payload:{}),code:(payload&&payload.code)||response.status,msg:(payload&&payload.msg)||'HTTP '+response.status}; return payload; }catch(err){ log(method,path,'NET',err.message,Math.round(performance.now()-started)); return {code:'NET',msg:'网络错误：'+err.message}; } }
  function dataOf(r){ return r && (r.data !== undefined ? r.data : r); }
  function setConnection(){ const online=!!session.token; $('.connection').classList.toggle('online',online); $('#connectionText').textContent=online?(session.userInfo?.username||'已登录'):'未登录'; $('#logoutBtn').hidden=!online; }
  function setAuthMessage(id,text,ok=false){ const el=$(id);el.textContent=text||'';el.classList.toggle('ok',!!ok); }

  function route(){ if(!session.token){ $('#page-login').classList.remove('hidden'); $('#appPage').classList.add('hidden'); return; } $('#page-login').classList.add('hidden'); $('#appPage').classList.remove('hidden'); const name=(location.hash||'#/agents').replace('#/',''); const valid=['agents','providers','models','tools','chat'].includes(name)?name:'agents'; $$('.route-page').forEach(x=>x.classList.toggle('hidden',x.id!=='route-'+valid)); $$('.side-nav a').forEach(x=>x.classList.toggle('active',x.dataset.route===valid)); if(valid==='agents') refreshAgents(); if(valid==='providers') refreshProviders(); if(valid==='models') refreshModels(); if(valid==='tools') refreshTools(); if(valid==='chat') refreshChatAgents(); }
  function renderUser(){ const u=session.userInfo||{}; $('#userName').textContent=u.username||'当前用户'; $('#userRole').textContent=u.role||'已登录用户'; $('#userAvatar').textContent=(u.username||'A').slice(0,1).toUpperCase(); setConnection(); }

  async function refreshAgents(){ const r=await api('POST','/api/v1/agents/list',{name:$('#agentSearch').value.trim(),status:$('#agentStatusFilter').value,page:1,pageSize:100}); if(r.code&&r.code!==200){$('#agentNotice').textContent=errorText(r);return;} const d=dataOf(r)||{}; agents=d.agents||[]; $('#agentCount').textContent=d.total??agents.length; renderAgents(); }
  async function refreshModelData(){ if(!providers.length) await refreshProviders(); const r=await api('GET','/api/v1/llms?page=1&pageSize=100&modelType=chat'); if(r.code&&r.code!==200){toast(errorText(r),true);return;} const d=dataOf(r)||{}; models=d.llms||[]; }
  function renderAgents(){ const list=$('#agentList'); list.innerHTML=agents.map(a=>`<article class="agent-card card ${esc(a.status)}"><div class="card-top"><div class="agent-icon">${esc(a.icon||'✦')}</div><div><div class="agent-name">${esc(a.name)}</div><span class="pill ${esc(a.status)}">${statusName(a.status)}</span></div></div><p class="agent-desc">${esc(a.description||'尚未添加描述')}</p><div class="agent-meta"><span>${esc(a.modelProvider||'未配置厂商')}</span><span>${esc(a.modelName||'未配置模型')}</span></div><div class="agent-actions"><button class="button ghost small" data-edit-agent="${a.id}">编辑</button><button class="button ghost small" data-chat-agent="${a.id}" ${a.status!=='published'?'disabled':''}>对话</button></div></article>`).join(''); $('#agentEmpty').classList.toggle('hidden',agents.length!==0); $$('[data-edit-agent]').forEach(b=>b.onclick=()=>openModal('agent',agents.find(a=>a.id===b.dataset.editAgent))); $$('[data-chat-agent]').forEach(b=>b.onclick=()=>{location.hash='#/chat'; setTimeout(()=>{$('#chatAgent').value=b.dataset.chatAgent; $('#chatAgent').dispatchEvent(new Event('change'));},200);}); }
  function statusName(v){ return ({draft:'草稿',published:'已发布',archived:'已归档',active:'可用',inactive:'停用'})[v]||v||'—'; }

  async function refreshProviders(){ const r=await api('GET','/api/v1/provider-configs?page=1&pageSize=100'); if(r.code&&r.code!==200){toast(errorText(r),true);return;} const d=dataOf(r)||{};providers=d.providerConfigs||[]; renderProviders(); fillProviderOptions(); }
  function renderProviders(){ $('#providerList').innerHTML=providers.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.provider)}</small></td><td>${esc(p.apiBase||'默认地址')}</td><td>${p.hasApiKey?esc(p.apiKey||'已配置'):'未配置'}</td><td><span class="pill ${esc(p.status)}">${statusName(p.status)}</span></td><td>${formatTime(p.updatedAt)}</td><td><div class="row-actions"><button class="button ghost small" data-edit-provider="${p.id}">编辑</button><button class="button ghost small danger" data-del-provider="${p.id}">删除</button></div></td></tr>`).join(''); $('#providerEmpty').classList.toggle('hidden',providers.length!==0); $$('[data-edit-provider]').forEach(b=>b.onclick=()=>openModal('provider',providers.find(p=>p.id===b.dataset.editProvider))); $$('[data-del-provider]').forEach(b=>b.onclick=()=>deleteProvider(b.dataset.delProvider)); }
  function fillProviderOptions(){ const options='<option value="">全部厂商配置</option>'+providers.map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.provider)}</option>`).join(''); const filter=$('#modelProviderFilter'); const keep=filter.value;filter.innerHTML=options;filter.value=keep; }
  async function deleteProvider(id){ const p=providers.find(x=>x.id===id);if(!confirm(`删除厂商配置「${p?.name||''}」？关联模型存在时后端会拒绝删除。`))return;const r=await api('DELETE','/api/v1/provider-configs/'+id);if(r.code&&r.code!==200)return toast(errorText(r),true);toast('已删除厂商配置');refreshProviders(); }

  async function refreshModels(){ if(!providers.length) await refreshProviders(); const config=$('#modelProviderFilter').value, type=$('#modelTypeFilter').value;let path='/api/v1/llms?page=1&pageSize=100';if(config)path+='&providerConfigId='+enc(config);if(type)path+='&modelType='+enc(type); const r=await api('GET',path);if(r.code&&r.code!==200){toast(errorText(r),true);return;}const d=dataOf(r)||{};models=d.llms||[];renderModels(); }
  function providerName(id){ const p=providers.find(x=>x.id===id);return p?`${p.name} · ${p.provider}`:'未知配置'; }
  function renderModels(){ $('#modelList').innerHTML=models.map(m=>`<tr><td><b>${esc(m.name)}</b><small>${esc(m.description||'无描述')}</small></td><td><code>${esc(m.modelName)}</code></td><td>${esc(providerName(m.providerConfigId))}</td><td>${esc(m.modelType)}</td><td><span class="pill ${esc(m.status)}">${statusName(m.status)}</span></td><td><div class="row-actions"><button class="button ghost small" data-edit-model="${m.id}">编辑</button><button class="button ghost small danger" data-del-model="${m.id}">删除</button></div></td></tr>`).join('');$('#modelEmpty').classList.toggle('hidden',models.length!==0);$$('[data-edit-model]').forEach(b=>b.onclick=()=>openModal('model',models.find(m=>m.id===b.dataset.editModel)));$$('[data-del-model]').forEach(b=>b.onclick=()=>deleteModel(b.dataset.delModel)); }
  async function deleteModel(id){const m=models.find(x=>x.id===id);if(!confirm(`删除模型「${m?.name||''}」？`))return;const r=await api('DELETE','/api/v1/llms/'+id);if(r.code&&r.code!==200)return toast(errorText(r),true);toast('已删除模型');refreshModels();}

  async function refreshTools(){const name=$('#toolSearch').value.trim(),type=$('#toolTypeFilter').value;let path='/api/v1/tools?page=1&pageSize=100';if(name)path+='&name='+enc(name);if(type)path+='&type='+enc(type);const r=await api('GET',path);if(r.code&&r.code!==200){toast(errorText(r),true);return;}const d=dataOf(r)||{};tools=d.list||[];renderTools();}
  function renderTools(){$('#toolList').innerHTML=tools.map(t=>`<tr><td><b>${esc(t.name)}</b><small>${esc(t.description||'无描述')}</small></td><td>${esc(t.type)}</td><td><span class="pill ${t.isEnable?'active':'inactive'}">${t.isEnable?'启用':'停用'}</span></td><td>${formatTime(t.updatedAt)}</td><td><div class="row-actions"><button class="button ghost small" data-edit-tool="${t.id}">编辑</button><button class="button ghost small" data-test-tool="${t.id}" ${t.type!=='system'||!t.isEnable?'disabled':''}>测试</button><button class="button ghost small danger" data-del-tool="${t.id}">删除</button></div></td></tr>`).join('');$('#toolEmpty').classList.toggle('hidden',tools.length!==0);$$('[data-edit-tool]').forEach(b=>b.onclick=()=>openModal('tool',tools.find(t=>t.id===b.dataset.editTool)));$$('[data-test-tool]').forEach(b=>b.onclick=()=>testTool(b.dataset.testTool));$$('[data-del-tool]').forEach(b=>b.onclick=()=>deleteTool(b.dataset.delTool));}
  async function testTool(id){const tool=tools.find(t=>t.id===id);const city=prompt(`测试「${tool?.name||''}」，请输入城市`,'北京');if(city===null)return;const r=await api('POST','/api/v1/tools/'+id+'/test',{params:{city,extensions:'base'}});if(r.code&&r.code!==200)return toast(errorText(r),true);const d=dataOf(r)||{};toast(d.success?'工具测试成功':(d.message||'工具测试失败'),!d.success);}
  async function deleteTool(id){const tool=tools.find(t=>t.id===id);if(!confirm(`删除工具「${tool?.name||''}」？`))return;const r=await api('DELETE','/api/v1/tools/'+id);if(r.code&&r.code!==200)return toast(errorText(r),true);toast('已删除工具');refreshTools();}

  async function openModal(type,item=null){
    if(type==='agent'){ await refreshModelData(); if(!tools.length) await refreshTools(); if(item?.id){ const detail=await api('GET','/api/v1/agents/'+item.id); if(!detail.code||detail.code===200) item={...item,...(dataOf(detail)||{})}; } }
    const formItem = item || {};
    editing={type,item:item || null};
    $('#modalBackdrop').classList.remove('hidden');
    const labels={agent:'智能体',provider:'厂商配置',model:'模型',tool:'工具'};
    $('#modalTitle').textContent=`${item?'编辑':'新建'}${labels[type]||''}`;
    const form=$('#entityForm');
    if(type==='agent') form.innerHTML=agentForm(formItem);
    if(type==='provider') form.innerHTML=providerForm(formItem);
    if(type==='model') form.innerHTML=modelForm(formItem);
    if(type==='tool') form.innerHTML=toolForm(formItem);
    const toolType=form.querySelector('select[name="toolType"]'); if(toolType){ const sync=()=>form.querySelector('.mcp-fields')?.classList.toggle('hidden',toolType.value!=='mcp'); toolType.onchange=sync; sync(); }
    form.onsubmit=submitEntity;
  }
  function closeModal(){$('#modalBackdrop').classList.add('hidden');editing=null;}
  function modelKey(provider, name){ return `${provider}::${name}`; }
  function providerForModel(m){ return providers.find(p=>p.id===m.providerConfigId); }
  function agentModelOptions(a={}){
    const current = a.modelProvider && a.modelName ? modelKey(a.modelProvider, a.modelName) : '';
    const chatModels = models.filter(m=>m.modelType==='chat');
    let options = '<option value="">未配置模型（保存为草稿）</option>';
    options += chatModels.map(m=>{
      const p=providerForModel(m), provider=p?.provider||'';
      return `<option value="${esc(modelKey(provider,m.modelName))}" ${current===modelKey(provider,m.modelName)?'selected':''}>${esc(p?.name||provider)} · ${esc(m.modelName)}${m.status!=='active'?'（已停用）':''}</option>`;
    }).join('');
    if(current && !chatModels.some(m=>{const p=providerForModel(m);return modelKey(p?.provider||'',m.modelName)===current;})){
      options += `<option value="${esc(current)}" selected>${esc(a.modelProvider)} · ${esc(a.modelName)}（当前配置未登记）</option>`;
    }
    return options;
  }
  function agentForm(a={}){const qdata=a.suggestedQuestions||{};const qitems=Array.isArray(qdata)?qdata:(Array.isArray(qdata.items)?qdata.items:[]);const qs=qitems.map(x=>typeof x==='string'?x:x.text).join('\n');const selected=new Set((a.tools||[]).map(t=>t.id));const options=tools.map(t=>`<option value="${t.id}" ${selected.has(t.id)?'selected':''}>${esc(t.name)} · ${esc(t.type)}</option>`).join('');return `<div class="form-row"><label>名称<input name="name" value="${esc(a.name||'')}" required></label><label>状态<select name="status"><option value="draft" ${a.status==='draft'?'selected':''}>草稿</option><option value="published" ${a.status==='published'?'selected':''}>已发布（必须有可用模型）</option><option value="archived" ${a.status==='archived'?'selected':''}>已归档</option></select></label></div><label>描述<input name="description" value="${esc(a.description||'')}" placeholder="这个智能体做什么？"></label><label>图标（字符或 URL）<input name="icon" value="${esc(a.icon||'')}" placeholder="例如 ✦"></label><label>系统提示词<textarea name="systemPrompt" placeholder="定义角色、能力边界和回答风格">${esc(a.systemPrompt||'')}</textarea></label><label>关联 Chat 模型<select name="modelRef">${agentModelOptions(a)}</select><span class="field-help">这里选择的是模型管理中的“模型标识”，例如 <code>qwen-plus</code>、<code>gpt-4o-mini</code>；必须与模型管理中的 modelName 完全一致。</span></label><label>关联工具（按住 Ctrl 多选，保存时整体替换）<select name="toolIds" multiple size="4">${options}</select></label><label>开场白<textarea name="openingDialogue" placeholder="你好，我可以帮你…">${esc(a.openingDialogue||'')}</textarea></label><label>建议问题（每行一个）<textarea name="suggestedQuestions" placeholder="帮我总结这段内容\n给我一个执行计划">${esc(qs)}</textarea></label>${modalButtons()}`;}
  function providerForm(p={}){return `<div class="form-row"><label>配置名称<input name="name" value="${esc(p.name||'')}" required placeholder="我的 OpenAI"></label><label>厂商标识<select name="provider"><option value="openai" ${p.provider==='openai'?'selected':''}>openai</option><option value="qwen" ${p.provider==='qwen'?'selected':''}>qwen</option><option value="ollama" ${p.provider==='ollama'?'selected':''}>ollama</option></select></label></div><label>描述<input name="description" value="${esc(p.description||'')}" placeholder="可选说明"></label><label>API Key<input name="apiKey" type="password" ${p.id?'placeholder="留空则保持原密钥"':'required'}><span class="field-help">密钥仅提交给后端；列表中仅可见掩码。</span></label><label>API Base<input name="apiBase" value="${esc(p.apiBase||'')}" placeholder="留空使用 SDK 默认地址；Ollama 通常为 http://localhost:11434"></label><label>状态<select name="status"><option value="active" ${p.status!=='inactive'?'selected':''}>可用 active</option><option value="inactive" ${p.status==='inactive'?'selected':''}>停用 inactive</option></select></label>${modalButtons()}`;}
  function toolForm(t={}){if(!t.id)return `<label>系统工具名称<input name="name" value="get_weather" required><span class="field-help">必须与注册名一致。当前内置工具只有 get_weather。</span></label><label>类型<select name="toolType"><option value="system">system</option><option value="mcp">mcp</option></select></label><div class="mcp-fields hidden"><label>MCP 类型<input name="mcpType" placeholder="sse"></label><label>MCP 地址<input name="mcpUrl" placeholder="https://example.com/sse"></label><label class="check-line"><input name="authenticationRequired" type="checkbox">需要认证</label><label>凭据类型<input name="credentialType" placeholder="bearer"></label></div>${modalButtons()}`;return `<label>描述<textarea name="description">${esc(t.description||'')}</textarea></label><label>启用状态<select name="isEnable"><option value="true" ${t.isEnable!==false?'selected':''}>启用</option><option value="false" ${t.isEnable===false?'selected':''}>停用</option></select></label><span class="field-help">系统工具的名称和参数由代码注册表维护，这里只能改启用状态。</span>${modalButtons()}`;}
  function modelForm(m={}){const options=providers.map(p=>`<option value="${p.id}" ${m.providerConfigId===p.id?'selected':''}>${esc(p.name)} · ${esc(p.provider)}</option>`).join('');return `<label>显示名称<input name="name" value="${esc(m.name||'')}" required placeholder="GPT-4o Mini"></label><div class="form-row"><label>所属厂商配置<select name="providerConfigId" required><option value="">请选择</option>${options}</select></label><label>模型标识<input name="modelName" value="${esc(m.modelName||'')}" required placeholder="gpt-4o-mini"></label></div><label>描述<input name="description" value="${esc(m.description||'')}"></label><div class="form-row"><label>模型类型<select name="modelType"><option value="chat" ${m.modelType!=='embedding'&&m.modelType!=='vision'?'selected':''}>chat</option><option value="embedding" ${m.modelType==='embedding'?'selected':''}>embedding</option><option value="vision" ${m.modelType==='vision'?'selected':''}>vision</option></select></label><label>状态<select name="status"><option value="active" ${m.status!=='inactive'?'selected':''}>可用 active</option><option value="inactive" ${m.status==='inactive'?'selected':''}>停用 inactive</option></select></label></div><div class="form-row"><label>最大 tokens<input name="maxTokens" type="number" min="0" value="${esc(m.config?.maxTokens||'')}"></label><label>温度（0–2）<input name="temperature" type="number" min="0" max="2" step="0.1" value="${esc(m.config?.temperature??'')}"></label></div>${modalButtons()}`;}
  function modalButtons(){return '<div class="modal-actions"><button class="button ghost" id="cancelModal" type="button">取消</button><button class="button primary" type="submit">保存配置</button></div>';}
  function formValues(form){return Object.fromEntries(new FormData(form).entries());}
  async function submitEntity(e){e.preventDefault();const raw=formValues(e.target),{type,item}=editing;let r;if(type==='agent'){let modelProvider='',modelName='';if(raw.modelRef){[modelProvider,modelName]=raw.modelRef.split('::');}const body={name:raw.name,description:raw.description,icon:raw.icon,status:raw.status,systemPrompt:raw.systemPrompt,modelProvider,modelName,openingDialogue:raw.openingDialogue,suggestedQuestions:{items:raw.suggestedQuestions.split('\n').map(x=>x.trim()).filter(Boolean)}};r=item?await api('PUT','/api/v1/agents/update',{id:item.id,...body}):await api('POST','/api/v1/agents/create',{name:raw.name,description:raw.description,status:'draft'});let agentID=item?.id;if(!item&&(!r.code||r.code===200)){const created=dataOf(r)||{};agentID=created.id||created.agent?.id;if(agentID&&raw.modelRef)r=await api('PUT','/api/v1/agents/update',{id:agentID,...body});}if(agentID&&(!r.code||r.code===200)){const selected=[...e.target.elements.toolIds.selectedOptions].map(option=>({id:option.value,type:(tools.find(t=>t.id===option.value)||{}).type||'system'}));const toolResult=await api('POST','/api/v1/agents/'+agentID+'/tools/batch',{tools:selected});if(toolResult.code&&toolResult.code!==200)r=toolResult;}}if(type==='provider'){const body={name:raw.name,provider:raw.provider,description:raw.description,apiBase:raw.apiBase,status:raw.status};if(raw.apiKey)body.apiKey=raw.apiKey;r=item?await api('PUT','/api/v1/provider-configs/'+item.id,body):await api('POST','/api/v1/provider-configs/',{...body,apiKey:raw.apiKey});}if(type==='model'){const body={name:raw.name,description:raw.description,providerConfigId:raw.providerConfigId,modelName:raw.modelName,modelType:raw.modelType,status:raw.status,config:{maxTokens:Number(raw.maxTokens)||0,temperature:Number(raw.temperature)||0,topP:0}};r=item?await api('PUT','/api/v1/llms/'+item.id,body):await api('POST','/api/v1/llms/',body);}if(type==='tool'){if(item){const body={description:raw.description,isEnable:raw.isEnable==='true'};if(item.type==='mcp')body.mcpConfig={type:raw.mcpType,url:raw.mcpUrl,authenticationRequired:raw.authenticationRequired==='on',credentialType:raw.credentialType};r=await api('PUT','/api/v1/tools/'+item.id,body);}else{const body={name:raw.name,toolType:raw.toolType,isEnable:true};if(raw.toolType==='mcp')body.mcpConfig={type:raw.mcpType,url:raw.mcpUrl,authenticationRequired:raw.authenticationRequired==='on',credentialType:raw.credentialType};r=await api('POST','/api/v1/tools',body);}}if(r.code&&r.code!==200){toast(errorText(r),true);return;}toast('保存成功');closeModal();if(type==='agent')refreshAgents();if(type==='provider'){refreshProviders();}if(type==='model')refreshModels();if(type==='tool')refreshTools();}

  async function refreshChatAgents(){if(!agents.length) await refreshAgents(); if(!models.length) await refreshModels(); const published=agents.filter(a=>a.status==='published'); const select=$('#chatAgent'),keep=select.value;select.innerHTML='<option value="">请选择已发布智能体</option>'+published.map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(a.modelName||'未配置模型')}</option>`).join('');select.value=keep;updateChatInfo();}
  function updateChatInfo(){const a=agents.find(x=>x.id===$('#chatAgent').value);$('#chatTitle').textContent=a?a.name:'等待选择智能体';$('#chatAgentInfo').textContent=a?`模型：${a.modelProvider||'—'} / ${a.modelName||'—'}\n状态：${statusName(a.status)}`:'请选择一个智能体';}
  function addBubble(kind,text){const history=$('#chatHistory');const welcome=$('.chat-welcome',history);if(welcome)welcome.remove();const n=document.createElement('div');n.className='bubble '+kind;n.textContent=text;history.append(n);history.scrollTop=history.scrollHeight;return n;}
  async function streamChat(message){const agentId=$('#chatAgent').value;if(!agentId)return toast('请先选择已发布智能体',true);if(chatAbort)return;addBubble('user',message);const bubble=addBubble('assistant','');$('#streamState').textContent='streaming';$('#chatSend').disabled=true;chatAbort=new AbortController();const started=performance.now();try{const res=await fetch(API_BASE+'/api/v1/agents/chat',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.token,'Accept':'text/event-stream'},body:JSON.stringify({agentId,message}),signal:chatAbort.signal});if(!res.ok){const text=await res.text();log('POST','/api/v1/agents/chat',res.status,text,Math.round(performance.now()-started));bubble.classList.add('error');bubble.textContent='请求失败：'+text;return;}log('POST','/api/v1/agents/chat',res.status,'SSE connected',Math.round(performance.now()-started));const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';for(;;){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split('\n\n');buffer=frames.pop();for(const frame of frames){const line=frame.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const raw=line.slice(5).trim();if(raw==='[DONE]'){log('SSE','[DONE]',200,undefined);continue;}if(raw.startsWith('[ERROR]')){bubble.classList.add('error');bubble.textContent+=raw.replace(/^\[ERROR\]\s*/, '');log('SSE','error',500,raw);continue;}try{const event=JSON.parse(raw);const content=event.content||'';if(content)bubble.textContent+=content;if(event.isErr)bubble.classList.add('error');}catch(_){bubble.textContent+=raw;}$('#chatHistory').scrollTop=$('#chatHistory').scrollHeight;}}}catch(err){if(err.name!=='AbortError'){bubble.classList.add('error');bubble.textContent='流式连接错误：'+err.message;log('SSE','/agents/chat','NET',err.message);}}finally{chatAbort=null;$('#streamState').textContent='idle';$('#chatSend').disabled=false;}}
  function formatTime(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('zh-CN',{hour12:false});}

  function bind(){ $('#toolSearchBtn').onclick=refreshTools;$('#toolSearch').addEventListener('keydown',e=>{if(e.key==='Enter')refreshTools();}); $$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$('#loginForm').classList.toggle('hidden',t.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',t.dataset.authTab!=='register');}); $('#loginForm').onsubmit=async e=>{e.preventDefault();const f=formValues(e.target);const r=await api('POST','/api/v1/auth/login',{username:f.username,password:f.password},false);if(r.code!==200)return setAuthMessage('#loginMessage',errorText(r));const d=dataOf(r)||{};session={token:d.token||'',refreshToken:d.refreshToken||'',userInfo:d.userInfo||null};save();renderUser();location.hash='#/agents';route();toast('登录成功');}; $('#registerForm').onsubmit=async e=>{e.preventDefault();const f=formValues(e.target);const r=await api('POST','/api/v1/auth/register',f,false);setAuthMessage('#registerMessage',r.code===200?'注册成功，请在邮箱完成验证后登录。':errorText(r),r.code===200);}; $('#logoutBtn').onclick=()=>{if(chatAbort)chatAbort.abort();clear();renderUser();location.hash='#/login';route();}; $('#agentSearchBtn').onclick=refreshAgents;$('#agentSearch').addEventListener('keydown',e=>{if(e.key==='Enter')refreshAgents();});$('#modelSearchBtn').onclick=refreshModels;$$('[data-open-modal]').forEach(b=>b.onclick=async()=>{if(b.dataset.openModal==='model'&&!providers.length)await refreshProviders();openModal(b.dataset.openModal);});$('#closeModalBtn').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal();};$('#entityForm').addEventListener('click',e=>{if(e.target.id==='cancelModal')closeModal();});$('#clearLogBtn').onclick=()=>$('#requestLog').innerHTML='<p class="muted">等待 API 请求…</p>';$('#chatAgent').onchange=updateChatInfo;$('#clearChatBtn').onclick=()=>{$('#chatHistory').innerHTML='<div class="chat-welcome">会话已清空，可以继续开始新的验收对话。</div>';};$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;input.value='';streamChat(text);};$('#chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit();}};window.addEventListener('hashchange',route); }
  load();bind();renderUser();$('#apiBaseLabel').textContent=(API_BASE||location.origin)+'/api';route();
})();
